
language: java

os: linux

dist: xenial

install: true

jdk: openjdk11

services:
    - xvfb

git:
    depth: false

before_script:
    - export DISPLAY=:99.0
    
addons:
  sonarcloud:
    organization: "subhas-dev"
    token: 
      secure: 441802eb558a1046f23a532f67d00867d145fa4d
      
jobs:
    include:
        - stage: Gradle
          script: ./gradlew test
        - stage: Maven
          script: mvn test sonar:sonar && bash <(curl -s https://codecov.io/bash)

