language: java
sudo: false
dist: xenial
install: true

addons:
  sonarcloud:
    organization: "subhas-dev"
    token: ${{ secrets.SONAR_TOKEN }}
    #  secure: "d0e59488c638fbaa326f2f1c5ecf19cea2eaaee9" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # 35
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=Subhas-Dev_sonarjavalab
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  # 31 failed
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Subhas-Dev_sonarjavalab
  # 29 passed - Return travis ci : paased 
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report

#addons:
#  sonarcloud:
#    organization: "subhas-dev"
#    token: ${{ secrets.SONAR_TOKEN }}

#script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean verify sonar:sonar -Pcoverage
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Subhas-Dev_sonarjavalab
 
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  #- if [ "$JAVA_HOME" = "/usr/local/lib/jvm/openjdk11" ]; then mvn sonar:sonar; fi
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
