sudo: false
install: true

addons:
  sonarcloud:
    organization: "subhas-dev"
    token:
      secure: "e2b8ecbf04d0edfbe81f1067cb37aa0bbcac8b1d"

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

